### ISSUE TITLE
Change in Admin

### ISSUE THREAD

**Issue by JaCrispy1** [Mantuss/E-Challan#7]
Sidebar link is not working e.g. (History link does not redirect anywhere).

**Comment by rikesh-mahat** [comment]
![Screenshot (100)](https://user-images.githubusercontent.com/94281365/162767284-40941d81-746f-40a5-98ba-33919d39c2f1.png)

**Comment by rikesh-mahat** [comment]
Updated the sidebar links, links re-direct you to their respective pages.
