### ISSUE TITLE
Change in Traffic UI and fixing preview bug

### ISSUE THREAD

**Issue by JaCrispy1** [Mantuss/E-Challan#8]
- Change the UI of Traffic Login Page. It doesn't looks user friendly.

- The Challan ID is not shown in the preview of the Challan.

**Comment by abhinavm07** [comment]
![277843867_1419132648524368_6804569497068561533_n](https://user-images.githubusercontent.com/88830300/162766343-fbbabfd9-d695-4b17-9035-6ddc916015ce.png)

**Comment by abhinavm07** [comment]
Preview fixed and UI updated
